### ISSUE TITLE
Entering price in dollars doesn't set the price in bits

### ISSUE THREAD

**Issue by mikehearn** [hivewallet/hive-osx#462]
In the send window, for some reason whilst it converts bits -> USD, the same isn't true the other way around. It just sits on 0 bits the whole time.

**Comment by jsuder** [comment]
Hm, I got a report once about this happening with pounds, but I couldn't reproduce it then.

I've tried now on my Yosemite machine and it looks like it's happening here. I'll take a look at this tomorrow.

**Comment by jsuder** [comment]
Huh, looks like a bug in `NSDecimalNumber` on Yosemite...

![screen shot 2015-01-10 at 01 56 39](https://cloud.githubusercontent.com/assets/28465/5689747/06fc3e06-986c-11e4-8607-a4e51f61ed47.png)

The exact same thing returns correct result (123456789) on Mavericks.
